#__________________________________________
### ROOT
GET http://localhost:8000/api HTTP/1.1




#__________________________________________
### API
GET http://localhost:8000/api/routes HTTP/1.1




#__________________________________________
### MODELS [user]
# read
GET http://localhost:8000/api/user/get HTTP/1.1

###
GET http://localhost:8000/api/user/get/06be2240bbe34a049eec165678582a5b HTTP/1.1


# write
###
POST http://localhost:8000/api/user/create HTTP/1.1
Content-Type: application/json

{
    "username": "LNM",
    "password": "password",
    "fullname": "LNM",
    "email":    "lnm@gmail.com"
}

###
PUT http://localhost:8000/api/user/update/06be2240bbe34a049eec165678582a5b HTTP/1.1
Content-Type: application/json

{
    "username": "LNMUpdated",
    "password": "passwordUpdated",
    "fullname": "LNMUpdated",
    "email":    "lnmupdated@gmail.com"
}

###
DELETE http://localhost:8000/api/user/delete/06be2240bbe34a049eec165678582a5b HTTP/1.1




#__________________________________________
### MODELS [item]
# read
GET http://localhost:8000/api/item/get HTTP/1.1

###
GET http://localhost:8000/api/item/get/1 HTTP/1.1


# write
###
POST http://localhost:8000/api/item/create HTTP/1.1
Content-Type: application/json

{
    "name": "Car",
    "active": true,
    "user": "06be2240bbe34a049eec165678582a5b"
}

###
PUT http://localhost:8000/api/item/update/ebd8cd09c14a468592a5558fc8ce0684 HTTP/1.1
Content-Type: application/json

{
    "name": "CarUpdated",
    "active": false,
    "user": "06be2240bbe34a049eec165678582a5b"
}

###
DELETE http://localhost:8000/api/item/delete/ebd8cd09c14a468592a5558fc8ce0684 HTTP/1.1




#__________________________________________
### MODELS [category]
# read
GET http://localhost:8000/api/category/get HTTP/1.1

###
GET http://localhost:8000/api/category/get/1 HTTP/1.1


# write
###
POST http://localhost:8000/api/category/create HTTP/1.1
Content-Type: application/json

{
    "name": "Horror",
    "color": "Gray"
}

###
PUT http://localhost:8000/api/category/update/1 HTTP/1.1
Content-Type: application/json

{
    "name": "Nature",
    "color": "White"
}

###
DELETE http://localhost:8000/api/category/delete/1 HTTP/1.1