version: '3'

services:
  db:
    container_name: db_mysql
    image: mysql:8
    restart: always
    environment:
      - MYSQL_USER="root"
      - MYSQL_ROOT_PASSWORD="Lucas123456!"
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
      - MYSQL_DATABASE="django"
    volumes:
      - /tmp/app/mysqld:/var/run/mysqld
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
  
  backend:
    container_name: backend_python
    image: backend-python:django
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    entrypoint: ["./wait.sh"]
    depends_on:
      - db
    ports:
      - "8000:8000"
