version: '3'

services:
  db:
    container_name: db_mysql
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DBSQL_PSWD}
      - MYSQL_DATABASE=${DBSQL_NAME}
    ports:
      - "3306:3306"
  
  backend:
    container_name: backend_python
    image: backend-python:django
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    entrypoint: ["./wait.sh"]
    depends_on:
      - db
    ports:
      - "8000:8000"
